#!/usr/bin/env python3
"""kb-graph: Auto-generated knowledge graph for any repo.

Scans a git repo, discovers how all files connect via imports, wiki-links,
and config references, and produces KB_INDEX.md + graph.html.
"""

import argparse
import json
import os
import re
import subprocess
import sys
from collections import defaultdict
from datetime import datetime, timezone


# ── Constants ──────────────────────────────────────────────────────────────

IGNORE_DIRS = {
    ".git", "__pycache__", "node_modules", ".venv", "venv",
    "dist", "build", ".tox", ".mypy_cache", ".pytest_cache", "egg-info",
}

# Files generated by kb-graph — skip during scanning
IGNORE_FILES = {"KB_INDEX.md"}

CODE_EXTS = {".py"}
MD_EXTS = {".md"}
CONFIG_EXTS = {".yaml", ".yml", ".json", ".toml"}
SHELL_EXTS = {".sh", ".bash"}
R_EXTS = {".R"}
NF_EXTS = {".nf"}
ALL_TRACKED_EXTS = CODE_EXTS | MD_EXTS | CONFIG_EXTS | SHELL_EXTS | R_EXTS | NF_EXTS

PALETTE = [
    "#58a6ff", "#3fb950", "#d29922", "#f85149", "#bc8cff",
    "#f778ba", "#39d2c0", "#ff9a3c", "#56d364", "#e06c9f",
]


# ── File Discovery ─────────────────────────────────────────────────────────

def load_ignore_patterns(repo_root):
    """Load ignore patterns from .phoamignore and .gitignore."""
    patterns = []
    for filename in (".phoamignore", ".gitignore"):
        path = os.path.join(repo_root, filename)
        if os.path.isfile(path):
            with open(path, "r", errors="ignore") as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith("#"):
                        continue
                    if line.startswith("!"):
                        continue  # negation not supported
                    patterns.append(line)
    return patterns


def matches_ignore(rel_path, patterns):
    """Check if a relative path matches any ignore pattern."""
    from fnmatch import fnmatch

    parts = rel_path.split("/")
    for pattern in patterns:
        # Directory pattern (ends with /)
        if pattern.endswith("/"):
            dir_name = pattern.rstrip("/")
            for part in parts[:-1]:  # check directory components
                if fnmatch(part, dir_name):
                    return True
            # Also check if the full relative directory path matches
            rel_dir = "/".join(parts[:-1])
            if rel_dir and (fnmatch(rel_dir, dir_name) or fnmatch(rel_dir + "/", pattern)):
                return True
        else:
            # File pattern
            basename = parts[-1]
            if fnmatch(basename, pattern):
                return True
            if fnmatch(rel_path, pattern):
                return True
    return False


def discover_files(repo_root):
    """Walk the repo and return tracked file paths (relative to repo_root)."""
    ignore_patterns = load_ignore_patterns(repo_root)
    tracked = []

    for dirpath, dirnames, filenames in os.walk(repo_root):
        # Filter out ignored directories in-place
        dirnames[:] = [
            d for d in dirnames
            if d not in IGNORE_DIRS
            and not matches_ignore(
                os.path.relpath(os.path.join(dirpath, d), repo_root) + "/",
                ignore_patterns,
            )
        ]

        for fname in filenames:
            full_path = os.path.join(dirpath, fname)
            rel_path = os.path.relpath(full_path, repo_root)

            # Normalize path separators
            rel_path = rel_path.replace(os.sep, "/")

            # Check extension
            _, ext = os.path.splitext(fname)
            if ext not in ALL_TRACKED_EXTS:
                continue

            # Skip generated files
            if fname in IGNORE_FILES:
                continue

            # Skip empty __init__.py
            if fname == "__init__.py":
                try:
                    if os.path.getsize(full_path) == 0:
                        continue
                except OSError:
                    continue

            # Check ignore patterns
            if matches_ignore(rel_path, ignore_patterns):
                continue

            tracked.append(rel_path)

    return sorted(tracked)


# ── Description Extraction ─────────────────────────────────────────────────

def get_description(filepath, repo_root):
    """Extract a short description from a file."""
    full_path = os.path.join(repo_root, filepath)
    ext = os.path.splitext(filepath)[1]

    try:
        with open(full_path, "r", errors="ignore") as f:
            content = f.read(4096)
    except OSError:
        return ""

    if ext == ".py":
        # Try module docstring (triple-quoted)
        m = re.match(
            r'^(?:\s*#[^\n]*\n)*\s*(?:"""(.*?)"""|\'\'\'(.*?)\'\'\')',
            content,
            re.DOTALL,
        )
        if m:
            doc = m.group(1) or m.group(2)
            return doc.strip().split("\n")[0].strip()
        # Fall back to first non-shebang comment
        for line in content.split("\n"):
            line = line.strip()
            if line.startswith("#!"):
                continue
            if line.startswith("#"):
                return line.lstrip("# ").strip()
            if line and not line.startswith("#"):
                break
        return ""

    elif ext == ".md":
        for line in content.split("\n"):
            line = line.strip()
            if line.startswith("# "):
                return line[2:].strip()
        return ""

    else:
        return ""


# ── Module Resolution ──────────────────────────────────────────────────────

def resolve_module(module_path, current_file, tracked_set):
    """Resolve a Python module path to a tracked file.

    Handles both absolute imports (core.config) and relative imports (.auth).
    Returns the resolved file path or None.
    """
    if module_path.startswith("."):
        # Relative import
        dots = len(module_path) - len(module_path.lstrip("."))
        rest = module_path[dots:]

        current_dir = os.path.dirname(current_file)
        for _ in range(dots - 1):
            current_dir = os.path.dirname(current_dir)

        if rest:
            candidate_base = (
                current_dir + "/" + rest.replace(".", "/") if current_dir else rest.replace(".", "/")
            )
        else:
            return None

        for suffix in (".py", "/__init__.py"):
            candidate = candidate_base + suffix
            if candidate in tracked_set:
                return candidate
        return None
    else:
        # Absolute import — convert dots to path separators
        file_path = module_path.replace(".", "/")

        # Try exact match first
        for suffix in (".py", "/__init__.py"):
            candidate = file_path + suffix
            if candidate in tracked_set:
                return candidate

        # Try suffix match (module relative to a source root like src/)
        for tracked in tracked_set:
            for suffix in (".py", "/__init__.py"):
                target = "/" + file_path + suffix
                if tracked.endswith(target):
                    return tracked

        return None


# ── Wiki-link Resolution ──────────────────────────────────────────────────

def resolve_wikilink(link_text, tracked_set):
    """Resolve a [[wiki-link]] to a tracked file path.

    Rules:
    1. If link contains '/' and has a file extension -> direct path
    2. Otherwise -> basename match (with or without extension)

    Returns (resolved_path, section) or (None, section).
    """
    section = None
    if "#" in link_text:
        link_text, section = link_text.split("#", 1)

    # Strip display text (pipe syntax: [[file|display]])
    if "|" in link_text:
        link_text = link_text.split("|")[0]

    link_text = link_text.strip()
    if not link_text:
        return None, section

    # Direct path reference (contains / and has extension)
    if "/" in link_text and "." in link_text.split("/")[-1]:
        if link_text in tracked_set:
            return link_text, section
        return None, section

    # Basename matching
    has_ext = "." in link_text
    matches = []

    for f in tracked_set:
        basename = os.path.basename(f)
        stem = os.path.splitext(basename)[0]

        if has_ext:
            if basename == link_text:
                matches.append(f)
        else:
            if stem == link_text:
                matches.append(f)

    if len(matches) == 1:
        return matches[0], section
    elif len(matches) > 1:
        # Ambiguous — return first match, could warn
        return matches[0], section

    return None, section


# ── Parsers ────────────────────────────────────────────────────────────────

def parse_python(filepath, repo_root, tracked_set):
    """Parse a Python file for imports and Design wiki-links."""
    edges = []
    full_path = os.path.join(repo_root, filepath)

    try:
        with open(full_path, "r", errors="ignore") as f:
            content = f.read()
    except OSError:
        return edges

    seen_targets = set()

    for line in content.split("\n"):
        stripped = line.strip()

        # Check for # Design: [[link]] comments anywhere in the line
        wl_match = re.search(r"#\s*Design:\s*\[\[(.+?)\]\]", stripped)
        if wl_match:
            target, section = resolve_wikilink(wl_match.group(1), tracked_set)
            if target and target != filepath and target not in seen_targets:
                seen_targets.add(target)
                edges.append({
                    "from": filepath, "to": target,
                    "type": "wiki-link", "section": section,
                })

        # Skip pure comment lines for import parsing
        if stripped.startswith("#") or not stripped:
            continue

        # from .X import Y (relative import)
        m = re.match(r"^from\s+(\.+[\w.]*)\s+import\s+(.+)", stripped)
        if m:
            module_base = m.group(1)
            names_str = m.group(2).split("#")[0]  # strip inline comments
            names = [n.strip().split()[0].strip(",") for n in names_str.split(",")]

            resolved_set = set()
            for name in names:
                if name == "*" or not name:
                    continue
                # For relative imports, try module_base.name as submodule
                dots = len(module_base) - len(module_base.lstrip("."))
                rest = module_base[dots:]
                if rest:
                    full_module = module_base + "." + name
                else:
                    full_module = "." * dots + name
                resolved = resolve_module(full_module, filepath, tracked_set)
                if resolved and resolved != filepath:
                    resolved_set.add(resolved)

            # If no submodules resolved, try the base module
            if not resolved_set:
                resolved = resolve_module(module_base, filepath, tracked_set)
                if resolved and resolved != filepath:
                    resolved_set.add(resolved)

            for target in resolved_set:
                if target not in seen_targets:
                    seen_targets.add(target)
                    edges.append({
                        "from": filepath, "to": target,
                        "type": "import", "section": None,
                    })
            continue

        # from X.Y import Z (absolute import)
        m = re.match(r"^from\s+([\w.]+)\s+import\s+(.+)", stripped)
        if m:
            module_base = m.group(1)
            names_str = m.group(2).split("#")[0]
            names = [n.strip().split()[0].strip(",") for n in names_str.split(",")]

            resolved_set = set()
            for name in names:
                if name == "*" or not name:
                    continue
                full_module = module_base + "." + name
                resolved = resolve_module(full_module, filepath, tracked_set)
                if resolved and resolved != filepath:
                    resolved_set.add(resolved)

            if not resolved_set:
                resolved = resolve_module(module_base, filepath, tracked_set)
                if resolved and resolved != filepath:
                    resolved_set.add(resolved)

            for target in resolved_set:
                if target not in seen_targets:
                    seen_targets.add(target)
                    edges.append({
                        "from": filepath, "to": target,
                        "type": "import", "section": None,
                    })
            continue

        # import X.Y.Z
        m = re.match(r"^import\s+([\w.]+)", stripped)
        if m:
            module = m.group(1)
            resolved = resolve_module(module, filepath, tracked_set)
            if resolved and resolved != filepath and resolved not in seen_targets:
                seen_targets.add(resolved)
                edges.append({
                    "from": filepath, "to": resolved,
                    "type": "import", "section": None,
                })
            continue

    return edges


def extract_exports(filepath):
    """Extract top-level function signatures and class definitions from a Python file.

    Returns a list of strings like:
        "apply_transform(data: DataFrame, config: Config, strict: bool = True) -> DataFrame"
        "class TransformConfig"
        "class PipelineError(Exception)"

    Skips private functions (_prefixed), nested functions, and methods inside classes.
    Handles multiline signatures (parentheses spanning multiple lines).
    """
    try:
        with open(filepath, "r", errors="ignore") as f:
            lines = f.readlines()
    except OSError:
        return []

    exports = []
    indent_in_class = False  # True when we're inside a class body
    i = 0

    while i < len(lines):
        line = lines[i]
        stripped = line.rstrip()
        leading_spaces = len(line) - len(line.lstrip())

        # Track whether we're inside a class body (indented)
        if stripped and not stripped.startswith("#"):
            if leading_spaces == 0:
                indent_in_class = False

        # Top-level class definition
        if leading_spaces == 0 and re.match(r"^class\s+", stripped):
            m = re.match(r"^class\s+(\w+)(?:\(([^)]*)\))?\s*:", stripped)
            if m:
                name = m.group(1)
                bases = m.group(2)
                if bases:
                    exports.append(f"class {name}({bases.strip()})")
                else:
                    exports.append(f"class {name}")
                indent_in_class = True
            i += 1
            continue

        # Top-level function definition (not inside a class, not private)
        if leading_spaces == 0 and re.match(r"^def\s+", stripped) and not indent_in_class:
            m = re.match(r"^def\s+(\w+)\s*\(", stripped)
            if m:
                name = m.group(1)
                # Skip private functions
                if name.startswith("_"):
                    i += 1
                    continue

                # Collect the full signature (may span multiple lines)
                sig_lines = [stripped]
                # Check if parentheses are balanced
                paren_depth = stripped.count("(") - stripped.count(")")
                j = i + 1
                while paren_depth > 0 and j < len(lines):
                    sig_lines.append(lines[j].rstrip())
                    paren_depth += lines[j].count("(") - lines[j].count(")")
                    j += 1

                full_sig = " ".join(s.strip() for s in sig_lines)

                # Extract: def name(params) -> return_type:
                sig_match = re.match(
                    r"def\s+(\w+)\s*\(([^)]*)\)\s*(?:->\s*(.+?))?\s*:",
                    full_sig,
                )
                if sig_match:
                    func_name = sig_match.group(1)
                    params_raw = sig_match.group(2)
                    return_type = sig_match.group(3)

                    # Clean up params: collapse whitespace, strip trailing commas
                    params = ", ".join(
                        p.strip() for p in params_raw.split(",") if p.strip()
                    )

                    if return_type:
                        exports.append(f"{func_name}({params}) -> {return_type.strip()}")
                    else:
                        exports.append(f"{func_name}({params})")

            i += 1
            continue

        # Inside a class body — skip methods (they're indented)
        if leading_spaces > 0 and indent_in_class and re.match(r"\s+def\s+", line):
            i += 1
            continue

        i += 1

    return exports


def parse_markdown(filepath, repo_root, tracked_set):
    """Parse a Markdown file for [[wiki-links]]."""
    edges = []
    full_path = os.path.join(repo_root, filepath)

    try:
        with open(full_path, "r", errors="ignore") as f:
            content = f.read()
    except OSError:
        return edges

    seen_targets = set()

    for match in re.finditer(r"\[\[(.+?)\]\]", content):
        link_text = match.group(1)
        target, section = resolve_wikilink(link_text, tracked_set)
        if target and target != filepath and target not in seen_targets:
            seen_targets.add(target)
            edges.append({
                "from": filepath, "to": target,
                "type": "wiki-link", "section": section,
            })

    return edges


def parse_config(filepath, repo_root, tracked_set):
    """Parse a config file for file path references."""
    edges = []
    full_path = os.path.join(repo_root, filepath)
    ext = os.path.splitext(filepath)[1]

    try:
        with open(full_path, "r", errors="ignore") as f:
            content = f.read()
    except OSError:
        return edges

    # Extract string values
    values = set()

    if ext == ".json":
        try:
            data = json.loads(content)
            _extract_json_strings(data, values)
        except (json.JSONDecodeError, ValueError):
            pass
    else:
        # YAML / TOML — extract quoted strings
        for m in re.finditer(r'''["']([^"']+)["']''', content):
            values.add(m.group(1).strip())
        # Also unquoted values that look like file paths
        for m in re.finditer(
            r":\s*(\S+\.(?:py|md|yaml|yml|json|toml|sh|R|nf))\s*$",
            content,
            re.MULTILINE,
        ):
            values.add(m.group(1).strip())

    seen_targets = set()
    for value in values:
        if value in tracked_set and value != filepath and value not in seen_targets:
            seen_targets.add(value)
            edges.append({
                "from": filepath, "to": value,
                "type": "config-ref", "section": None,
            })

    return edges


def _extract_json_strings(obj, result):
    """Recursively extract all string values from a JSON object."""
    if isinstance(obj, str):
        result.add(obj)
    elif isinstance(obj, dict):
        for v in obj.values():
            _extract_json_strings(v, result)
    elif isinstance(obj, list):
        for item in obj:
            _extract_json_strings(item, result)


# ── Graph Building ─────────────────────────────────────────────────────────

def get_group(filepath):
    """Determine the component group for a file.

    Used for KB_INDEX.md section headers and graph.html node colors.
    """
    parts = filepath.split("/")
    if len(parts) == 1:
        return "root"
    if parts[0] == "src":
        if len(parts) == 2:
            return "src"
        return "src/" + parts[1]
    return parts[0]


def get_file_type(filepath):
    """Determine the file type (code, doc, config)."""
    ext = os.path.splitext(filepath)[1]
    if ext in CODE_EXTS:
        return "code"
    if ext in MD_EXTS:
        return "doc"
    if ext in CONFIG_EXTS:
        return "config"
    return "asset"


PARSER_MAP = {
    ".py": parse_python,
    ".md": parse_markdown,
    ".yaml": parse_config,
    ".yml": parse_config,
    ".json": parse_config,
    ".toml": parse_config,
}


def build_graph(repo_root):
    """Scan the repo and build the full dependency graph."""
    repo_root = os.path.abspath(repo_root)
    tracked_files = discover_files(repo_root)
    tracked_set = set(tracked_files)

    nodes = {}
    edges = []

    # Build nodes
    for filepath in tracked_files:
        nodes[filepath] = {
            "description": get_description(filepath, repo_root),
            "group": get_group(filepath),
            "type": get_file_type(filepath),
        }

    # Parse edges
    for filepath in tracked_files:
        ext = os.path.splitext(filepath)[1]
        parser = PARSER_MAP.get(ext)
        if parser:
            file_edges = parser(filepath, repo_root, tracked_set)
            edges.extend(file_edges)

    # Deduplicate edges
    seen = set()
    unique_edges = []
    for edge in edges:
        key = (edge["from"], edge["to"], edge["type"])
        if key not in seen:
            seen.add(key)
            unique_edges.append(edge)

    return {"nodes": nodes, "edges": unique_edges}


# ── Display Names ──────────────────────────────────────────────────────────

def get_display_name(filepath, from_path=None):
    """Get a human-readable display name for a file.

    If from_path is given and both files share the same directory,
    use relative notation (e.g., '.auth').
    """
    stem = os.path.splitext(os.path.basename(filepath))[0]

    if from_path:
        from_dir = os.path.dirname(from_path)
        to_dir = os.path.dirname(filepath)
        if from_dir == to_dir:
            return "." + stem

    # Strip src/ prefix and convert to module notation
    path = filepath
    if path.startswith("src/"):
        path = path[4:]
    mod_path = os.path.splitext(path)[0].replace("/", ".")
    return mod_path


# ── Output: KB_INDEX.md ───────────────────────────────────────────────────

def write_kb_index(graph, repo_root):
    """Generate KB_INDEX.md from the graph."""
    nodes = graph["nodes"]
    edges = graph["edges"]

    # Compute inbound and outbound edges per node
    outbound = defaultdict(list)  # node -> list of (target, edge)
    inbound = defaultdict(list)   # node -> list of (source, edge)
    for edge in edges:
        outbound[edge["from"]].append(edge)
        inbound[edge["to"]].append(edge)

    # Find orphans (no inbound or outbound edges)
    orphan_nodes = []
    connected_nodes = {}
    for path, meta in sorted(nodes.items()):
        if not outbound[path] and not inbound[path]:
            orphan_nodes.append(path)
        else:
            connected_nodes[path] = meta

    # Group connected nodes
    groups = defaultdict(list)
    for path, meta in sorted(connected_nodes.items()):
        groups[meta["group"]].append(path)

    # Stats
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    node_count = len(nodes)
    edge_count = len(edges)
    orphan_count = len(orphan_nodes)

    lines = []
    lines.append("# KB_INDEX.md")
    lines.append(
        f"> Auto-generated by kb-graph — do not edit manually.\n"
        f"> Last rebuilt: {now} | Nodes: {node_count} | Edges: {edge_count} | Orphans: {orphan_count}"
    )
    lines.append("")
    lines.append("---")
    lines.append("")

    # Write each group
    for group_name in sorted(groups.keys()):
        lines.append(f"## {group_name}")
        lines.append("")

        for filepath in groups[group_name]:
            meta = nodes[filepath]
            basename = os.path.basename(filepath)
            desc = meta["description"]

            # Build the node entry
            if desc:
                lines.append(f"- **{basename}** — {desc}")
            else:
                lines.append(f"- **{basename}**")

            file_type = meta["type"]

            if file_type == "code":
                # Imports (outbound import edges)
                import_edges = [e for e in outbound[filepath] if e["type"] == "import"]
                if import_edges:
                    import_names = [
                        f"`{get_display_name(e['to'], filepath)}`"
                        for e in import_edges
                    ]
                    lines.append(f"  - imports: {', '.join(import_names)}")

                # Used by (inbound import edges)
                used_by_edges = [e for e in inbound[filepath] if e["type"] == "import"]
                if used_by_edges:
                    if len(used_by_edges) >= 5:
                        lines.append(f"  - used by {len(used_by_edges)} modules")
                    else:
                        used_names = [
                            f"`{get_display_name(e['from'], filepath)}`"
                            for e in used_by_edges
                        ]
                        lines.append(f"  - used by: {', '.join(used_names)}")

                # Doc links (inbound wiki-link edges from docs)
                doc_links = [
                    e for e in inbound[filepath]
                    if e["type"] == "wiki-link" and nodes.get(e["from"], {}).get("type") == "doc"
                ]
                if doc_links:
                    doc_names = []
                    for e in doc_links:
                        stem = os.path.splitext(os.path.basename(e["from"]))[0]
                        if e.get("section"):
                            doc_names.append(f"[[{stem}#{e['section']}]]")
                        else:
                            doc_names.append(f"[[{stem}]]")
                    lines.append(f"  - docs: {', '.join(doc_names)}")

            elif file_type == "doc":
                # Links to (outbound wiki-link edges)
                link_edges = [e for e in outbound[filepath] if e["type"] == "wiki-link"]
                if link_edges:
                    link_names = []
                    for e in link_edges:
                        stem = os.path.splitext(os.path.basename(e["to"]))[0]
                        ext = os.path.splitext(e["to"])[1]
                        if ext in CODE_EXTS:
                            link_names.append(f"[[{os.path.basename(e['to'])}]]")
                        else:
                            link_names.append(f"[[{stem}]]")
                    lines.append(f"  - links to: {', '.join(link_names)}")

            elif file_type == "config":
                # Config refs (outbound config-ref edges)
                ref_edges = [e for e in outbound[filepath] if e["type"] == "config-ref"]
                if ref_edges:
                    ref_names = [f"`{e['to']}`" for e in ref_edges]
                    lines.append(f"  - references: {', '.join(ref_names)}")

            lines.append("")

    # Orphans section
    if orphan_nodes:
        lines.append("## Orphans")
        lines.append("")
        for filepath in sorted(orphan_nodes):
            meta = nodes[filepath]
            desc = meta["description"]
            basename = os.path.basename(filepath)
            if desc:
                lines.append(f"- **{basename}** — {desc} (no connections)")
            else:
                lines.append(f"- **{basename}** — no connections")
            lines.append("")

    output = "\n".join(lines).rstrip() + "\n"
    output_path = os.path.join(repo_root, "KB_INDEX.md")
    with open(output_path, "w") as f:
        f.write(output)

    return output_path


# ── Output: graph.html ────────────────────────────────────────────────────

GRAPH_HTML_TEMPLATE = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Knowledge Graph</title>
<script src="https://d3js.org/d3.v7.min.js"></script>
<style>
* { margin: 0; padding: 0; box-sizing: border-box; }
body {
    background: #0d1117;
    color: #c9d1d9;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
    overflow: hidden;
}
#stats-bar {
    position: fixed; top: 0; left: 0; right: 0; height: 36px;
    background: #161b22; border-bottom: 1px solid #30363d;
    display: flex; align-items: center; padding: 0 16px;
    font-size: 13px; z-index: 10;
}
#stats-bar span { margin-right: 20px; color: #8b949e; }
#stats-bar .val { color: #58a6ff; font-weight: 600; }
#legend {
    position: fixed; top: 48px; right: 12px;
    background: #161b22; border: 1px solid #30363d; border-radius: 6px;
    padding: 12px; font-size: 12px; z-index: 10;
    max-height: calc(100vh - 120px); overflow-y: auto;
}
#legend h4 { margin: 0 0 8px 0; font-size: 13px; color: #c9d1d9; }
.leg-item { display: flex; align-items: center; margin: 3px 0; }
.leg-swatch {
    width: 12px; height: 12px; border-radius: 2px;
    margin-right: 8px; flex-shrink: 0;
}
.leg-sep { border-top: 1px solid #30363d; margin: 8px 0; }
.leg-line { width: 24px; height: 0; margin-right: 8px; flex-shrink: 0; }
#info-panel {
    position: fixed; top: 48px; left: 12px;
    background: #161b22; border: 1px solid #30363d; border-radius: 6px;
    padding: 16px; font-size: 13px; z-index: 10;
    max-width: 340px; display: none;
}
#info-panel h3 {
    margin: 0 0 10px 0; color: #58a6ff; font-size: 14px; word-break: break-all;
}
.field { margin: 6px 0; }
.field .lbl {
    color: #8b949e; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px;
}
.field .val { margin-top: 2px; }
.risk-low { color: #3fb950; }
.risk-medium { color: #d29922; }
.risk-high { color: #f85149; }
</style>
</head>
<body>
<div id="stats-bar">
    <span>Nodes: <span class="val" id="s-nodes">0</span></span>
    <span>Edges: <span class="val" id="s-edges">0</span></span>
    <span>Orphans: <span class="val" id="s-orphans">0</span></span>
</div>
<div id="legend"></div>
<div id="info-panel">
    <h3 id="ip-path"></h3>
    <div class="field"><div class="lbl">Description</div><div class="val" id="ip-desc"></div></div>
    <div class="field"><div class="lbl">Type</div><div class="val" id="ip-type"></div></div>
    <div class="field"><div class="lbl">Group</div><div class="val" id="ip-group"></div></div>
    <div class="field"><div class="lbl">Imports</div><div class="val" id="ip-imports"></div></div>
    <div class="field"><div class="lbl">Used by</div><div class="val" id="ip-usedby"></div></div>
    <div class="field"><div class="lbl">Risk</div><div class="val" id="ip-risk"></div></div>
</div>
<script>
const data = %%GRAPH_DATA%%;

document.getElementById("s-nodes").textContent = data.stats.nodes;
document.getElementById("s-edges").textContent = data.stats.edges;
document.getElementById("s-orphans").textContent = data.stats.orphans;

// Legend
const legEl = document.getElementById("legend");
let lh = '<h4>Components</h4>';
data.groups.forEach(g => {
    lh += '<div class="leg-item"><div class="leg-swatch" style="background:'+g.color+'"></div>'+g.name+'</div>';
});
lh += '<div class="leg-sep"></div><h4>Edge Types</h4>';
lh += '<div class="leg-item"><div class="leg-line" style="border-top:2px solid #8b949e"></div>import</div>';
lh += '<div class="leg-item"><div class="leg-line" style="border-top:2px dashed #8b949e"></div>wiki-link</div>';
lh += '<div class="leg-item"><div class="leg-line" style="border-top:2px dotted #8b949e"></div>config-ref</div>';
legEl.innerHTML = lh;

// Color map
const cm = {};
data.groups.forEach(g => { cm[g.name] = g.color; });

// Adjacency for blast radius
const adj = {};
data.nodes.forEach(n => { adj[n.id] = []; });
data.links.forEach(l => {
    const s = typeof l.source === 'object' ? l.source.id : l.source;
    const t = typeof l.target === 'object' ? l.target.id : l.target;
    if (!adj[s]) adj[s] = [];
    if (!adj[t]) adj[t] = [];
    adj[s].push(t);
    adj[t].push(s);
});

function blastRadius(nodeId, depth) {
    const depthMap = new Map([[nodeId, 0]]);
    let frontier = [nodeId];
    for (let d = 1; d <= depth; d++) {
        const next = [];
        for (const n of frontier) {
            for (const nb of (adj[n] || [])) {
                if (!depthMap.has(nb)) { depthMap.set(nb, d); next.push(nb); }
            }
        }
        frontier = next;
    }
    return depthMap;
}

// SVG setup
const width = window.innerWidth;
const height = window.innerHeight - 36;
const svg = d3.select("body").append("svg")
    .attr("width", width).attr("height", height)
    .style("position", "fixed").style("top", "36px").style("left", "0");
const g = svg.append("g");

// Zoom
svg.call(d3.zoom().scaleExtent([0.1, 10]).on("zoom", e => g.attr("transform", e.transform)));

// Simulation
const simulation = d3.forceSimulation(data.nodes)
    .force("link", d3.forceLink(data.links).id(d => d.id).distance(100))
    .force("charge", d3.forceManyBody().strength(-400))
    .force("center", d3.forceCenter(width / 2, height / 2))
    .force("collision", d3.forceCollide().radius(d => d.radius + 4));

// Edges
const link = g.selectAll(".link").data(data.links).join("line")
    .attr("stroke", "#30363d").attr("stroke-width", 1.5)
    .attr("stroke-opacity", 0.6)
    .attr("stroke-dasharray", d => {
        if (d.type === "wiki-link") return "6,3";
        if (d.type === "config-ref") return "2,3";
        return null;
    });

// Nodes
const node = g.selectAll(".node").data(data.nodes).join("circle")
    .attr("r", d => d.radius)
    .attr("fill", d => cm[d.group] || "#8b949e")
    .attr("stroke", "#0d1117").attr("stroke-width", 1.5)
    .style("cursor", "pointer");

// Labels
const label = g.selectAll(".label").data(data.nodes).join("text")
    .text(d => d.label).attr("font-size", 10).attr("fill", "#8b949e")
    .attr("text-anchor", "middle").attr("dy", d => d.radius + 14)
    .style("pointer-events", "none");

// Drag
const drag = d3.drag()
    .on("start", (e, d) => { if (!e.active) simulation.alphaTarget(0.3).restart(); d.fx = d.x; d.fy = d.y; })
    .on("drag", (e, d) => { d.fx = e.x; d.fy = e.y; })
    .on("end", (e, d) => { if (!e.active) simulation.alphaTarget(0); d.fx = null; d.fy = null; });
node.call(drag);

// Tick
simulation.on("tick", () => {
    link.attr("x1", d => d.source.x).attr("y1", d => d.source.y)
        .attr("x2", d => d.target.x).attr("y2", d => d.target.y);
    node.attr("cx", d => d.x).attr("cy", d => d.y);
    label.attr("x", d => d.x).attr("y", d => d.y);
});

// Click node — highlight blast radius with depth-based styling
node.on("click", (event, d) => {
    event.stopPropagation();
    const br = blastRadius(d.id, 2);

    // Depth 0 = clicked node (full bright, thick stroke)
    // Depth 1 = direct connectors (full opacity, highlighted stroke)
    // Depth 2 = transitive (slightly dimmed)
    // Outside = heavily dimmed
    node.attr("opacity", n => {
        if (!br.has(n.id)) return 0.08;
        const depth = br.get(n.id);
        return depth <= 1 ? 1 : 0.6;
    })
    .attr("stroke", n => {
        if (!br.has(n.id)) return "#0d1117";
        const depth = br.get(n.id);
        if (depth === 0) return "#fff";
        if (depth === 1) return "#58a6ff";
        return "#30363d";
    })
    .attr("stroke-width", n => {
        if (!br.has(n.id)) return 1.5;
        const depth = br.get(n.id);
        if (depth === 0) return 3;
        if (depth === 1) return 2.5;
        return 1.5;
    });

    link.attr("opacity", l => {
        const sIn = br.has(l.source.id);
        const tIn = br.has(l.target.id);
        if (sIn && tIn) {
            const maxD = Math.max(br.get(l.source.id), br.get(l.target.id));
            return maxD <= 1 ? 0.9 : 0.4;
        }
        return 0.03;
    })
    .attr("stroke", l => {
        const sIn = br.has(l.source.id);
        const tIn = br.has(l.target.id);
        if (sIn && tIn) {
            const maxD = Math.max(br.get(l.source.id), br.get(l.target.id));
            return maxD <= 1 ? "#58a6ff" : "#30363d";
        }
        return "#30363d";
    });

    label.attr("opacity", n => {
        if (!br.has(n.id)) return 0.05;
        const depth = br.get(n.id);
        return depth <= 1 ? 1 : 0.5;
    });

    const imports = data.links.filter(l => l.source.id === d.id).map(l => l.target.id);
    const usedBy = data.links.filter(l => l.target.id === d.id).map(l => l.source.id);
    const grps = new Set();
    br.forEach((depth, nId) => { const nd = data.nodes.find(x => x.id === nId); if (nd) grps.add(nd.group); });
    const risk = grps.size >= 3 ? "HIGH" : grps.size === 2 ? "MEDIUM" : "LOW";
    const d1count = [...br.values()].filter(v => v === 1).length;
    const d2count = [...br.values()].filter(v => v === 2).length;

    document.getElementById("ip-path").textContent = d.id;
    document.getElementById("ip-desc").textContent = d.description || "\u2014";
    document.getElementById("ip-type").textContent = d.type;
    document.getElementById("ip-group").textContent = d.group;
    document.getElementById("ip-imports").textContent = imports.join(", ") || "\u2014";
    document.getElementById("ip-usedby").textContent = usedBy.join(", ") || "\u2014";
    const riskEl = document.getElementById("ip-risk");
    riskEl.textContent = risk + " (" + d1count + " direct, " + d2count + " transitive)";
    riskEl.className = "val risk-" + risk.toLowerCase();
    document.getElementById("info-panel").style.display = "block";
});

// Click background — reset
svg.on("click", () => {
    node.attr("opacity", 1).attr("stroke", "#0d1117").attr("stroke-width", 1.5);
    link.attr("opacity", 0.6).attr("stroke", "#30363d");
    label.attr("opacity", 1);
    document.getElementById("info-panel").style.display = "none";
});
</script>
</body>
</html>"""


def write_graph_html(graph, repo_root):
    """Generate graph.html from the graph data."""
    nodes = graph["nodes"]
    edges = graph["edges"]

    # Compute degree per node
    degree = defaultdict(int)
    for edge in edges:
        degree[edge["from"]] += 1
        degree[edge["to"]] += 1

    # Build groups list
    group_names = sorted(set(meta["group"] for meta in nodes.values()))
    groups_data = [
        {"name": g, "color": PALETTE[i % len(PALETTE)]}
        for i, g in enumerate(group_names)
    ]

    # Build nodes data
    nodes_data = []
    for path, meta in sorted(nodes.items()):
        d = degree[path]
        radius = max(5, min(20, 5 + d * 2))
        nodes_data.append({
            "id": path,
            "label": os.path.basename(path),
            "group": meta["group"],
            "description": meta["description"],
            "type": meta["type"],
            "degree": d,
            "radius": radius,
        })

    # Build links data
    links_data = [
        {"source": e["from"], "target": e["to"], "type": e["type"]}
        for e in edges
    ]

    # Orphan count
    connected = set()
    for e in edges:
        connected.add(e["from"])
        connected.add(e["to"])
    orphan_count = sum(1 for path in nodes if path not in connected)

    graph_json = json.dumps({
        "nodes": nodes_data,
        "links": links_data,
        "groups": groups_data,
        "stats": {
            "nodes": len(nodes),
            "edges": len(edges),
            "orphans": orphan_count,
        },
    }, indent=2)

    html = GRAPH_HTML_TEMPLATE.replace("%%GRAPH_DATA%%", graph_json)

    output_path = os.path.join(repo_root, "graph.html")
    with open(output_path, "w") as f:
        f.write(html)

    return output_path


# ── Embedded Content (for init) ───────────────────────────────────────────

PRE_COMMIT_HOOK = r"""#!/usr/bin/env bash
# ── phoam_paint pre-commit hook ──
# Regenerate KB_INDEX.md before every commit
STAGED=$(git diff --cached --name-only --diff-filter=ACM)
HAS_TRACKED=$(echo "$STAGED" | grep -cE '\.(py|md|R|sh|yaml|yml|json|toml|nf)$' || true)
if [ "$HAS_TRACKED" -gt 0 ]; then
    echo "[pre-commit] Rebuilding KB_INDEX.md..."
    kb-graph rebuild .
    git add KB_INDEX.md
    echo "[pre-commit] KB_INDEX.md updated and staged."
fi
# ── end phoam_paint ──
"""

CLAUDE_MD_RULES = """
## Knowledge Graph Rules

1. **Read KB_INDEX.md first.** Before adding, modifying, or looking up content,
   read KB_INDEX.md to find the right files and understand their connections.
   KB_INDEX.md is auto-generated — never edit it by hand.

2. **Wiki-links in docs.** When editing any `.md` file, add `[[wiki-links]]` to
   cross-reference related docs and code. In Python files, use
   `# Design: [[doc-name#section]]` comments to link back to design docs.

3. **Query the graph before implementing.** Before starting a feature that
   touches multiple systems, run `kb-graph traverse <node> --depth 2` to
   discover all affected files. Read every file that surfaces before writing
   code. Or use `/check_graph <description>` for a full impact report.
"""

CHECK_GRAPH_SKILL = """\
---
name: check_graph
description: Analyze the impact of a proposed change by querying the project knowledge graph. Use before implementing any feature or fix that touches multiple files, after completing edits to verify blast radius, or when the user asks to check the graph. Runs kb-graph traverse/neighbors to surface affected files and returns a structured impact report.
---

# check_graph

Analyze the impact of a proposed change using the project's knowledge graph.

## When to use

- Before implementing a feature that may touch multiple systems
- After completing edits, to verify nothing was missed
- When the user says "/check_graph" or asks about impact/blast radius
- When you are unsure what files a change might affect

## Instructions

Determine what change is being analyzed. This comes from one of:
- The user's description (e.g., "/check_graph rename db_url to database_url")
- The current conversation context (e.g., you just edited config.py)
- Your own judgment (e.g., you're about to start a multi-file change)

Spawn an Explore agent to do the heavy lifting. This keeps the main context clean.

Use the Agent tool with subagent_type "Explore" and the following prompt,
filling in the change description:

---

You are analyzing the impact of a proposed change in this project.

**Change description**: <describe the change here>

**Your task**:

1. Run `kb-graph rebuild .` to ensure KB_INDEX.md is current.

2. Read KB_INDEX.md to understand the project structure.

3. Identify which modules/systems the change involves. Map them to entry-point
   files in the index.

4. For each entry point, run blast-radius queries:
   ```
   kb-graph traverse <entry-point> --depth 2
   kb-graph neighbors <entry-point>
   ```

5. Read every affected file the graph reveals. Do not skip any.

6. If the change involves creating a new module that parallels an existing one
   in the repo (e.g., a new `qc.py` in a sibling directory where one already
   exists), identify the existing analog as a **Template** in your report. The
   implementing agent should read the template before writing the new module.

7. Return a structured impact report:

### Change Summary
One sentence.

### Entry Points
Primary files that need edits. List each with its graph key.

### Blast Radius (via graph)
Files surfaced by traversal, grouped by depth, with WHY each is relevant.

### Template (if applicable)
Existing in-repo analog that the new module should follow. Include file path and
the key patterns to replicate (function signatures, return types, how it's wired
into its parent orchestrator/caller).

### Blockers & Decisions
- OPEN: questions that must be resolved before implementation
- DECIDED: existing decisions that constrain this change (quote the source)

### Impact Assessment
- Scope: Isolated (1-2 files) | Moderate (3-5) | Wide (6+)
- Breaking: Yes/No
- Risk: LOW / MEDIUM / HIGH (based on how many packages are in blast radius)
- Complexity: Simple | Moderate | Complex

### Recommended Approach
3-5 bullet plan.

### New Wiki-Links Needed
Specific [[wiki-links]] to add to connect this change into the graph.

---

Once the agent returns, display its report directly to the user.
"""

# Markers used to identify phoam_paint blocks in files
_HOOK_START = "# ── phoam_paint pre-commit hook ──"
_HOOK_END = "# ── end phoam_paint ──"
_RULES_START = "## Knowledge Graph Rules"
_GITIGNORE_LINES = ["KB_INDEX.md", "graph.html"]


# ── Query Helpers ─────────────────────────────────────────────────────────

def resolve_node(node_input, graph):
    """Resolve a user-provided node name to a graph node path.

    Tries exact match first, then basename match, then suffix match.
    Returns the resolved path or None.
    """
    nodes = graph["nodes"]

    # Exact match
    if node_input in nodes:
        return node_input

    # Basename match (e.g., "config.py" -> "src/core/config.py")
    matches = [p for p in nodes if os.path.basename(p) == node_input]
    if len(matches) == 1:
        return matches[0]

    # Suffix match (e.g., "core/config.py" -> "src/core/config.py")
    matches = [p for p in nodes if p.endswith("/" + node_input)]
    if len(matches) == 1:
        return matches[0]

    # Stem match without extension (e.g., "config" -> "src/core/config.py")
    if "." not in node_input:
        matches = [
            p for p in nodes
            if os.path.splitext(os.path.basename(p))[0] == node_input
        ]
        if len(matches) == 1:
            return matches[0]

    return None


def build_adjacency(graph):
    """Build inbound/outbound adjacency lists from graph edges."""
    outbound = defaultdict(list)  # node -> list of edges where node is source
    inbound = defaultdict(list)   # node -> list of edges where node is target
    for edge in graph["edges"]:
        outbound[edge["from"]].append(edge)
        inbound[edge["to"]].append(edge)
    return outbound, inbound


def bfs_blast_radius(node, graph, max_depth):
    """BFS from node, following inbound edges only, up to max_depth.

    Traces dependents: files that depend on the changed file, and files
    that depend on those, etc. This answers "what breaks if I change this?"

    Returns dict mapping node_path -> depth.
    """
    _outbound, inbound = build_adjacency(graph)
    depth_map = {node: 0}
    frontier = [node]

    for d in range(1, max_depth + 1):
        next_frontier = []
        for n in frontier:
            # Follow inbound edges: who depends on n?
            for edge in inbound.get(n, []):
                neighbor = edge["from"]
                if neighbor not in depth_map:
                    depth_map[neighbor] = d
                    next_frontier.append(neighbor)
        frontier = next_frontier

    return depth_map


def bfs_shortest_path(start, end, graph):
    """BFS shortest path from start to end, following edges in both directions.

    Returns list of node paths from start to end, or None if no path exists.
    """
    if start == end:
        return [start]

    outbound, inbound = build_adjacency(graph)
    visited = {start}
    # Queue entries: (current_node, path_so_far)
    queue = [(start, [start])]

    while queue:
        current, path = queue.pop(0)

        neighbors = set()
        for edge in outbound.get(current, []):
            neighbors.add(edge["to"])
        for edge in inbound.get(current, []):
            neighbors.add(edge["from"])

        for neighbor in sorted(neighbors):
            if neighbor == end:
                return path + [neighbor]
            if neighbor not in visited:
                visited.add(neighbor)
                queue.append((neighbor, path + [neighbor]))

    return None


def grep_references(target_node, file_path, repo_root, max_lines=5):
    """Grep a file for references to the target node's basename.

    Returns list of (line_number, line_text) tuples, capped at max_lines.
    """
    basename = os.path.splitext(os.path.basename(target_node))[0]
    full_path = os.path.join(repo_root, file_path)
    matches = []

    try:
        with open(full_path, "r", errors="ignore") as f:
            for i, line in enumerate(f, 1):
                if basename in line:
                    matches.append((i, line.rstrip()))
                    if len(matches) >= max_lines:
                        break
    except OSError:
        pass

    return matches


def get_edge_label(edge):
    """Get a short label describing the edge type and relationship."""
    etype = edge["type"]
    if etype == "import":
        return "imports"
    elif etype == "wiki-link":
        return "wiki-links to"
    elif etype == "config-ref":
        return "references"
    return etype


# ── CLI Commands ───────────────────────────────────────────────────────────

def cmd_rebuild(args):
    """Rebuild KB_INDEX.md and graph.html from current repo state."""
    repo_root = os.path.abspath(args.path)
    if not os.path.isdir(repo_root):
        print(f"Error: {repo_root} is not a directory", file=sys.stderr)
        sys.exit(1)

    graph = build_graph(repo_root)

    idx_path = write_kb_index(graph, repo_root)
    html_path = write_graph_html(graph, repo_root)

    node_count = len(graph["nodes"])
    edge_count = len(graph["edges"])
    connected = set()
    for e in graph["edges"]:
        connected.add(e["from"])
        connected.add(e["to"])
    orphan_count = sum(1 for n in graph["nodes"] if n not in connected)

    print(f"Rebuilt: {node_count} nodes, {edge_count} edges, {orphan_count} orphans")
    print(f"  {idx_path}")
    print(f"  {html_path}")


def cmd_init(args):
    """Initialize kb-graph in a repository."""
    repo_root = os.path.abspath(args.path)
    if not os.path.isdir(repo_root):
        print(f"Error: {repo_root} is not a directory", file=sys.stderr)
        sys.exit(1)

    # 1. Rebuild (produces KB_INDEX.md + graph.html)
    graph = build_graph(repo_root)
    idx_path = write_kb_index(graph, repo_root)
    html_path = write_graph_html(graph, repo_root)

    node_count = len(graph["nodes"])
    edge_count = len(graph["edges"])
    connected = set()
    for e in graph["edges"]:
        connected.add(e["from"])
        connected.add(e["to"])
    orphan_count = sum(1 for n in graph["nodes"] if n not in connected)
    print(f"Rebuilt: {node_count} nodes, {edge_count} edges, {orphan_count} orphans")
    print(f"  {idx_path}")
    print(f"  {html_path}")

    # 2. Pre-commit hook
    hooks_dir = os.path.join(repo_root, "scripts", "hooks")
    os.makedirs(hooks_dir, exist_ok=True)
    hook_path = os.path.join(hooks_dir, "pre-commit")

    hook_content = PRE_COMMIT_HOOK.strip() + "\n"
    if os.path.isfile(hook_path):
        with open(hook_path, "r") as f:
            existing = f.read()
        if _HOOK_START in existing:
            print(f"  pre-commit hook already contains phoam_paint block — skipping")
        else:
            # Strip shebang when appending — the existing file already has one
            block_only = "\n".join(
                line for line in hook_content.splitlines()
                if not line.startswith("#!")
            )
            with open(hook_path, "a") as f:
                f.write("\n" + block_only + "\n")
            print(f"  Appended phoam_paint hook to {hook_path}")
    else:
        with open(hook_path, "w") as f:
            f.write(hook_content)
        print(f"  Created {hook_path}")

    os.chmod(hook_path, 0o755)

    # Set git config core.hooksPath
    try:
        subprocess.run(
            ["git", "config", "core.hooksPath", "scripts/hooks"],
            cwd=repo_root, check=True, capture_output=True,
        )
        print("  Set git config core.hooksPath = scripts/hooks")
    except (subprocess.CalledProcessError, FileNotFoundError) as exc:
        print(f"  Warning: could not set git config core.hooksPath: {exc}",
              file=sys.stderr)

    # 3. Skill: .claude/skills/check_graph/SKILL.md
    skill_dir = os.path.join(repo_root, ".claude", "skills", "check_graph")
    os.makedirs(skill_dir, exist_ok=True)
    skill_path = os.path.join(skill_dir, "SKILL.md")
    with open(skill_path, "w") as f:
        f.write(CHECK_GRAPH_SKILL)
    print(f"  Created {skill_path}")

    # 4. CLAUDE.md — append Knowledge Graph Rules
    claude_md_path = os.path.join(repo_root, "CLAUDE.md")
    rules_block = CLAUDE_MD_RULES.strip() + "\n"
    if os.path.isfile(claude_md_path):
        with open(claude_md_path, "r") as f:
            existing = f.read()
        if _RULES_START in existing:
            print("  CLAUDE.md already contains Knowledge Graph Rules — skipping")
        else:
            with open(claude_md_path, "a") as f:
                f.write("\n" + rules_block)
            print(f"  Appended Knowledge Graph Rules to {claude_md_path}")
    else:
        with open(claude_md_path, "w") as f:
            f.write(rules_block)
        print(f"  Created {claude_md_path}")

    # 5. .gitignore — add KB_INDEX.md and graph.html
    gitignore_path = os.path.join(repo_root, ".gitignore")
    existing_lines = set()
    if os.path.isfile(gitignore_path):
        with open(gitignore_path, "r") as f:
            existing_lines = {line.strip() for line in f}

    lines_to_add = [ln for ln in _GITIGNORE_LINES if ln not in existing_lines]
    if lines_to_add:
        with open(gitignore_path, "a") as f:
            for ln in lines_to_add:
                f.write(ln + "\n")
        print(f"  Added {', '.join(lines_to_add)} to .gitignore")
    else:
        print("  .gitignore already contains KB_INDEX.md and graph.html — skipping")

    print("\nDone. kb-graph is set up for this project.")


def cmd_uninit(args):
    """Remove kb-graph from a repository."""
    repo_root = os.path.abspath(args.path)
    if not os.path.isdir(repo_root):
        print(f"Error: {repo_root} is not a directory", file=sys.stderr)
        sys.exit(1)

    # Gather what will be removed
    removals = []

    kb_index_path = os.path.join(repo_root, "KB_INDEX.md")
    if os.path.isfile(kb_index_path):
        removals.append(("file", "KB_INDEX.md"))

    graph_html_path = os.path.join(repo_root, "graph.html")
    if os.path.isfile(graph_html_path):
        removals.append(("file", "graph.html"))

    skill_path = os.path.join(repo_root, ".claude", "skills", "check_graph", "SKILL.md")
    if os.path.isfile(skill_path):
        removals.append(("file", ".claude/skills/check_graph/SKILL.md"))

    hook_path = os.path.join(repo_root, "scripts", "hooks", "pre-commit")
    if os.path.isfile(hook_path):
        with open(hook_path, "r") as f:
            hook_content = f.read()
        if _HOOK_START in hook_content:
            if _hook_has_other_content(hook_content):
                removals.append(("edit", "scripts/hooks/pre-commit (remove phoam_paint block)"))
            else:
                removals.append(("file", "scripts/hooks/pre-commit"))

    claude_md_path = os.path.join(repo_root, "CLAUDE.md")
    if os.path.isfile(claude_md_path):
        with open(claude_md_path, "r") as f:
            claude_content = f.read()
        if _RULES_START in claude_content:
            cleaned = _remove_rules_section(claude_content)
            if cleaned.strip():
                removals.append(("edit", "CLAUDE.md (remove Knowledge Graph Rules section)"))
            else:
                removals.append(("file", "CLAUDE.md"))

    gitignore_path = os.path.join(repo_root, ".gitignore")
    if os.path.isfile(gitignore_path):
        with open(gitignore_path, "r") as f:
            gitignore_lines = f.readlines()
        has_our_lines = any(line.strip() in _GITIGNORE_LINES for line in gitignore_lines)
        if has_our_lines:
            remaining = [ln for ln in gitignore_lines if ln.strip() not in _GITIGNORE_LINES]
            if any(ln.strip() for ln in remaining):
                removals.append(("edit", ".gitignore (remove KB_INDEX.md and graph.html lines)"))
            else:
                removals.append(("file", ".gitignore"))

    phoamignore_path = os.path.join(repo_root, ".phoamignore")
    if os.path.isfile(phoamignore_path):
        removals.append(("file", ".phoamignore"))

    # Check if git config core.hooksPath was set to scripts/hooks
    revert_hooks_path = False
    try:
        result = subprocess.run(
            ["git", "config", "--get", "core.hooksPath"],
            cwd=repo_root, capture_output=True, text=True,
        )
        if result.returncode == 0 and result.stdout.strip() == "scripts/hooks":
            revert_hooks_path = True
            removals.append(("config", "git config core.hooksPath (revert to default)"))
    except FileNotFoundError:
        pass

    if not removals:
        print("Nothing to remove — kb-graph is not initialized in this project.")
        return

    # Confirm before acting
    print("The following will be removed:\n")
    for kind, desc in removals:
        if kind == "file":
            print(f"  DELETE  {desc}")
        elif kind == "edit":
            print(f"  EDIT    {desc}")
        elif kind == "config":
            print(f"  REVERT  {desc}")

    print()
    try:
        answer = input("Proceed? [y/N] ").strip().lower()
    except (EOFError, KeyboardInterrupt):
        print("\nAborted.")
        return

    if answer != "y":
        print("Aborted.")
        return

    # Execute removals
    for kind, desc in removals:
        if kind == "file" and desc == "KB_INDEX.md":
            os.remove(kb_index_path)
            print(f"  Removed {desc}")

        elif kind == "file" and desc == "graph.html":
            os.remove(graph_html_path)
            print(f"  Removed {desc}")

        elif kind == "file" and desc == ".claude/skills/check_graph/SKILL.md":
            os.remove(skill_path)
            # Clean up empty directories
            skill_dir = os.path.dirname(skill_path)
            if os.path.isdir(skill_dir) and not os.listdir(skill_dir):
                os.rmdir(skill_dir)
                skills_dir = os.path.dirname(skill_dir)
                if os.path.isdir(skills_dir) and not os.listdir(skills_dir):
                    os.rmdir(skills_dir)
                    claude_dir = os.path.dirname(skills_dir)
                    if os.path.isdir(claude_dir) and not os.listdir(claude_dir):
                        os.rmdir(claude_dir)
            print(f"  Removed {desc}")

        elif kind == "file" and desc == "scripts/hooks/pre-commit":
            os.remove(hook_path)
            # Clean up empty directories
            hooks_dir = os.path.dirname(hook_path)
            if os.path.isdir(hooks_dir) and not os.listdir(hooks_dir):
                os.rmdir(hooks_dir)
                scripts_dir = os.path.dirname(hooks_dir)
                if os.path.isdir(scripts_dir) and not os.listdir(scripts_dir):
                    os.rmdir(scripts_dir)
            print(f"  Removed {desc}")

        elif kind == "edit" and "pre-commit" in desc:
            cleaned = _remove_hook_block(hook_content)
            with open(hook_path, "w") as f:
                f.write(cleaned)
            print(f"  {desc}")

        elif kind == "file" and desc == "CLAUDE.md":
            os.remove(claude_md_path)
            print(f"  Removed {desc}")

        elif kind == "edit" and "CLAUDE.md" in desc:
            cleaned = _remove_rules_section(claude_content)
            with open(claude_md_path, "w") as f:
                f.write(cleaned)
            print(f"  {desc}")

        elif kind == "file" and desc == ".gitignore":
            os.remove(gitignore_path)
            print(f"  Removed {desc}")

        elif kind == "edit" and ".gitignore" in desc:
            remaining = [ln for ln in gitignore_lines if ln.strip() not in _GITIGNORE_LINES]
            with open(gitignore_path, "w") as f:
                f.writelines(remaining)
            print(f"  {desc}")

        elif kind == "file" and desc == ".phoamignore":
            os.remove(phoamignore_path)
            print(f"  Removed {desc}")

        elif kind == "config":
            pass  # handled below

    if revert_hooks_path:
        try:
            subprocess.run(
                ["git", "config", "--unset", "core.hooksPath"],
                cwd=repo_root, check=True, capture_output=True,
            )
            print("  Reverted git config core.hooksPath")
        except (subprocess.CalledProcessError, FileNotFoundError):
            print("  Warning: could not revert git config core.hooksPath",
                  file=sys.stderr)

    print("\nDone. kb-graph has been removed from this project.")


def _remove_hook_block(content):
    """Remove the phoam_paint block from a pre-commit hook file."""
    lines = content.splitlines(keepends=True)
    result = []
    in_block = False
    for line in lines:
        if _HOOK_START in line:
            in_block = True
            # Also remove a preceding blank line if we added one
            if result and result[-1].strip() == "":
                result.pop()
            continue
        if in_block:
            if _HOOK_END in line:
                in_block = False
            continue
        result.append(line)
    return "".join(result)


def _hook_has_other_content(content):
    """True if a hook file has meaningful content outside the phoam_paint block."""
    cleaned = _remove_hook_block(content)
    # A bare shebang line is not meaningful on its own
    for line in cleaned.splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#!"):
            return True
    return False


def _remove_rules_section(content):
    """Remove the Knowledge Graph Rules section from CLAUDE.md.

    Removes from '## Knowledge Graph Rules' to the next '## ' heading or EOF.
    """
    lines = content.splitlines(keepends=True)
    result = []
    in_section = False
    for line in lines:
        if line.strip().startswith(_RULES_START):
            in_section = True
            # Remove a preceding blank line if present
            if result and result[-1].strip() == "":
                result.pop()
            continue
        if in_section:
            # Check if we hit the next section heading
            if line.startswith("## "):
                in_section = False
                result.append(line)
            continue
        result.append(line)
    # Remove trailing whitespace/newlines at end
    text = "".join(result)
    return text.rstrip("\n") + "\n" if text.strip() else ""


def cmd_neighbors(args):
    """Show direct connections of a node."""
    repo_root = os.path.abspath(args.path)
    if not os.path.isdir(repo_root):
        print(f"Error: {repo_root} is not a directory", file=sys.stderr)
        sys.exit(1)

    graph = build_graph(repo_root)
    node = resolve_node(args.node, graph)
    if node is None:
        print(f"Error: node '{args.node}' not found in graph", file=sys.stderr)
        sys.exit(1)

    outbound, inbound = build_adjacency(graph)

    out_edges = outbound.get(node, [])
    in_edges = inbound.get(node, [])

    print(f"NEIGHBORS: {node}")
    print()

    if out_edges:
        print(f"Outbound ({len(out_edges)}):")
        for edge in sorted(out_edges, key=lambda e: e["to"]):
            print(f"  -> {edge['to']} ({edge['type']})")
    else:
        print("Outbound: none")

    print()

    if in_edges:
        print(f"Inbound ({len(in_edges)}):")
        for edge in sorted(in_edges, key=lambda e: e["from"]):
            print(f"  <- {edge['from']} ({edge['type']})")
    else:
        print("Inbound: none")

    print()
    total = len(out_edges) + len(in_edges)
    print(f"Total: {total} connections")


def cmd_traverse(args):
    """Show blast radius from a node."""
    repo_root = os.path.abspath(args.path)
    if not os.path.isdir(repo_root):
        print(f"Error: {repo_root} is not a directory", file=sys.stderr)
        sys.exit(1)

    graph = build_graph(repo_root)
    node = resolve_node(args.node, graph)
    if node is None:
        print(f"Error: node '{args.node}' not found in graph", file=sys.stderr)
        sys.exit(1)

    max_depth = args.depth
    depth_map = bfs_blast_radius(node, graph, max_depth)
    outbound, inbound = build_adjacency(graph)

    print(f"BLAST RADIUS: {node}")
    print()

    # Group nodes by depth
    by_depth = defaultdict(list)
    for n, d in sorted(depth_map.items()):
        by_depth[d].append(n)

    # Depth 0 (the change)
    print("Depth 0 (the change)")
    print(f"  └── {node}")
    print()

    # For each subsequent depth level
    depth_labels = {
        1: "direct dependents — MUST review",
        2: "transitive — CHECK for breakage",
    }

    for d in range(1, max_depth + 1):
        nodes_at_depth = sorted(by_depth.get(d, []))
        if not nodes_at_depth:
            continue

        label = depth_labels.get(d, f"depth {d}")
        print(f"Depth {d} ({label})")

        for i, dep_node in enumerate(nodes_at_depth):
            is_last = (i == len(nodes_at_depth) - 1)
            connector = "└──" if is_last else "├──"
            indent = "      " if is_last else "│     "

            # Find the edge that connects this node into the blast radius.
            # dep_node is the source of an edge pointing to a closer-depth node
            # (because blast radius follows inbound edges: dep_node -> closer_node).
            edge_desc = ""
            for edge in outbound.get(dep_node, []):
                target = edge["to"]
                if target in depth_map and depth_map[target] < d:
                    target_name = os.path.splitext(os.path.basename(target))[0]
                    edge_desc = f" {get_edge_label(edge)} {target_name}"
                    break

            print(f"  {connector} {dep_node} ──{edge_desc}")

            # Grep for references to the target node in this file
            refs = grep_references(node, dep_node, repo_root)
            for line_no, line_text in refs:
                print(f"  {indent}L{line_no}: {line_text.strip()}")

        print()

    # Summary line
    direct_count = len(by_depth.get(1, []))
    transitive_count = sum(len(by_depth.get(d, [])) for d in range(2, max_depth + 1))

    # Risk = number of distinct groups in the radius
    groups_in_radius = set()
    for n in depth_map:
        if n in graph["nodes"]:
            groups_in_radius.add(graph["nodes"][n]["group"])

    risk_count = len(groups_in_radius)
    if risk_count >= 3:
        risk = "HIGH"
    elif risk_count == 2:
        risk = "MEDIUM"
    else:
        risk = "LOW"

    print(f"Summary: 1 changed → {direct_count} direct → {transitive_count} transitive | Risk: {risk} ({risk_count} groups in radius)")


def cmd_path(args):
    """Find shortest path between two nodes."""
    repo_root = os.path.abspath(args.repo_path)
    if not os.path.isdir(repo_root):
        print(f"Error: {repo_root} is not a directory", file=sys.stderr)
        sys.exit(1)

    graph = build_graph(repo_root)

    start = resolve_node(args.from_node, graph)
    if start is None:
        print(f"Error: node '{args.from_node}' not found in graph", file=sys.stderr)
        sys.exit(1)

    end = resolve_node(args.to_node, graph)
    if end is None:
        print(f"Error: node '{args.to_node}' not found in graph", file=sys.stderr)
        sys.exit(1)

    path = bfs_shortest_path(start, end, graph)

    if path is None:
        print(f"No path between {start} and {end}")
        sys.exit(0)

    outbound, inbound = build_adjacency(graph)

    print(f"PATH: {start} → {end} ({len(path) - 1} hops)")
    print()

    for i, node in enumerate(path):
        if i == 0:
            print(f"  {node}")
        else:
            # Find the edge connecting path[i-1] to path[i]
            prev = path[i - 1]
            edge_type = ""
            for edge in outbound.get(prev, []):
                if edge["to"] == node:
                    edge_type = edge["type"]
                    break
            if not edge_type:
                for edge in inbound.get(prev, []):
                    if edge["from"] == node:
                        edge_type = edge["type"]
                        break
            print(f"    ↓ {edge_type}")
            print(f"  {node}")


def cmd_orphans(args):
    """List files with no connections."""
    repo_root = os.path.abspath(args.path)
    if not os.path.isdir(repo_root):
        print(f"Error: {repo_root} is not a directory", file=sys.stderr)
        sys.exit(1)

    graph = build_graph(repo_root)

    connected = set()
    for edge in graph["edges"]:
        connected.add(edge["from"])
        connected.add(edge["to"])

    orphans = sorted(
        p for p in graph["nodes"] if p not in connected
    )

    print(f"ORPHANS: {len(orphans)} files with no connections")
    print()

    if orphans:
        for orphan in orphans:
            meta = graph["nodes"][orphan]
            desc = meta["description"]
            group = meta["group"]
            if desc:
                print(f"  {orphan} — {desc} [{group}]")
            else:
                print(f"  {orphan} [{group}]")
    else:
        print("  No orphans found — every file has at least one connection.")


def cmd_analyze(args):
    """Print graph statistics."""
    repo_root = os.path.abspath(args.path)
    if not os.path.isdir(repo_root):
        print(f"Error: {repo_root} is not a directory", file=sys.stderr)
        sys.exit(1)

    graph = build_graph(repo_root)
    nodes = graph["nodes"]
    edges = graph["edges"]

    # Basic counts
    node_count = len(nodes)
    edge_count = len(edges)

    connected = set()
    for edge in edges:
        connected.add(edge["from"])
        connected.add(edge["to"])
    orphan_count = sum(1 for n in nodes if n not in connected)

    # Degree per node (inbound + outbound)
    degree = defaultdict(int)
    for edge in edges:
        degree[edge["from"]] += 1
        degree[edge["to"]] += 1

    # Top-N most connected (top 5, or all if fewer)
    top_n = 5
    sorted_by_degree = sorted(degree.items(), key=lambda x: (-x[1], x[0]))
    top_nodes = sorted_by_degree[:top_n]

    # Edge type breakdown
    edge_types = defaultdict(int)
    for edge in edges:
        edge_types[edge["type"]] += 1

    # Group breakdown
    group_counts = defaultdict(int)
    for meta in nodes.values():
        group_counts[meta["group"]] += 1

    # File type breakdown
    type_counts = defaultdict(int)
    for meta in nodes.values():
        type_counts[meta["type"]] += 1

    # Print report
    print("GRAPH ANALYSIS")
    print()
    print(f"  Nodes: {node_count}")
    print(f"  Edges: {edge_count}")
    print(f"  Orphans: {orphan_count}")
    print()

    print("Edge types:")
    for etype in sorted(edge_types.keys()):
        print(f"  {etype}: {edge_types[etype]}")
    print()

    print("File types:")
    for ftype in sorted(type_counts.keys()):
        print(f"  {ftype}: {type_counts[ftype]}")
    print()

    print(f"Most connected (top {min(top_n, len(top_nodes))}):")
    for node_path, deg in top_nodes:
        print(f"  {node_path} ({deg} edges)")
    print()

    print(f"Groups ({len(group_counts)}):")
    for group in sorted(group_counts.keys()):
        print(f"  {group}: {group_counts[group]} files")


# ── Main ───────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        prog="kb-graph",
        description="Auto-generated knowledge graph for any repo.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    # rebuild
    p_rebuild = subparsers.add_parser("rebuild", help="Rebuild KB_INDEX.md and graph.html")
    p_rebuild.add_argument("path", nargs="?", default=".", help="Path to repo root (default: cwd)")
    p_rebuild.set_defaults(func=cmd_rebuild)

    # init
    p_init = subparsers.add_parser("init", help="Initialize kb-graph in a repo")
    p_init.add_argument("path", nargs="?", default=".", help="Path to repo root")
    p_init.set_defaults(func=cmd_init)

    # uninit
    p_uninit = subparsers.add_parser("uninit", help="Remove kb-graph from a repo")
    p_uninit.add_argument("path", nargs="?", default=".", help="Path to repo root")
    p_uninit.set_defaults(func=cmd_uninit)

    # neighbors
    p_neighbors = subparsers.add_parser("neighbors", help="Direct connections of a node")
    p_neighbors.add_argument("node", help="Node path")
    p_neighbors.add_argument("--path", default=".", help="Path to repo root")
    p_neighbors.set_defaults(func=cmd_neighbors)

    # traverse
    p_traverse = subparsers.add_parser("traverse", help="Blast radius from a node")
    p_traverse.add_argument("node", help="Node path")
    p_traverse.add_argument("--depth", type=int, default=2, help="Traversal depth (default: 2)")
    p_traverse.add_argument("--path", default=".", help="Path to repo root")
    p_traverse.set_defaults(func=cmd_traverse)

    # path
    p_path = subparsers.add_parser("path", help="Shortest path between two nodes")
    p_path.add_argument("from_node", metavar="from", help="Source node")
    p_path.add_argument("to_node", metavar="to", help="Target node")
    p_path.add_argument("--path", default=".", dest="repo_path", help="Path to repo root")
    p_path.set_defaults(func=cmd_path)

    # orphans
    p_orphans = subparsers.add_parser("orphans", help="List orphan files")
    p_orphans.add_argument("--path", default=".", help="Path to repo root")
    p_orphans.set_defaults(func=cmd_orphans)

    # analyze
    p_analyze = subparsers.add_parser("analyze", help="Graph statistics")
    p_analyze.add_argument("--path", default=".", help="Path to repo root")
    p_analyze.set_defaults(func=cmd_analyze)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
